version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - SECRET_KEY=your-production-secret-key-change-this-in-production
      - DATABASE_URL=sqlite:///instance/blog.db
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped

  # 開発環境用の設定
  web-dev:
    build: .
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-secret-key
      - DATABASE_URL=sqlite:///instance/blog.db
    volumes:
      - .:/app
      - ./instance:/app/instance
    command: python app.py